server:
  port: 9999
  context-path: /uaa
  session:
    cookie:
      secure: true
  compression:
          enabled: true
          mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
          min-response-size: 1024



spring:
  application:
    name: Authorization-Service
    admin:
      enabled: true
  http:
    encoding:
      charset: utf-8
      enabled: true
    multipart:
      enabled: true
      file-size-threshold: 1MB
      max-file-size: 20
      max-request-size: 10
#  jpa:
#    open-in-view: false
#    hibernate:
#      ddl-auto: none
#      naming:
#          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#          implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
security:
  oauth2:
    resource:
      filter-order: 3

