spring:
  application:
    name: Authorization-Service

eureka:
  instance:
    prefer-ip-address: false
    hostname: localhost
  client:
    allow-redirects: true
    enabled: true
    service-url: http://localhost:8761/eureka/
